### ISSUE TITLE
[Teams Library] The bot reports BadRequest when the message is empty

### ISSUE THREAD

**Issue by ArcturusZhang** [test-repo-billy/azure-rest-api-specs#3077]
### Bug Report

![image](https://github.com/test-repo-billy/azure-rest-api-specs/assets/10554446/70f7fcc2-5e94-4f0c-92da-35009afb33af)

**Comment by raych1** [comment]
whitespace message causes below exception.
```
Microsoft.Bot.Builder.Integration.AspNet.Core.CloudAdapter: Error: [OnTurnError] unhandled error : Something went wrong HTTP response failure status code: $BadRequest (Bad Request)

Microsoft.TeamsAI.Exceptions.AzureContentSafetyClientException: Something went wrong HTTP response failure status code: $BadRequest (Bad Request)
   at Microsoft.TeamsAI.AI.AzureContentSafety.AzureContentSafetyClient._ExecutePostRequest(String url, HttpContent content, CancellationToken cancellationToken)
   at Microsoft.TeamsAI.AI.AzureContentSafety.AzureContentSafetyClient.ExecuteTextModeration(AzureContentSafetyTextAnalysisRequest request)
   at Microsoft.TeamsAI.AI.Moderator.AzureContentSafetyModerator`1._HandleTextModeration(String text, Boolean isModelInput)
   at Microsoft.TeamsAI.AI.Moderator.AzureContentSafetyModerator`1.ReviewPrompt(ITurnContext turnContext, TState turnState, PromptTemplate prompt)
   at Microsoft.TeamsAI.AI.AI`1.ChainAsync(ITurnContext turnContext, TState turnState, PromptTemplate prompt, AIOptions`1 options, CancellationToken cancellationToken)
   at Microsoft.TeamsAI.AI.AI`1.ChainAsync(ITurnContext turnContext, TState turnState, String prompt, AIOptions`1 options, CancellationToken cancellationToken)
   at Microsoft.TeamsAI.Application`2._OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken)
   at Microsoft.TeamsAI.Application`2.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.MiddlewareSet.ReceiveActivityWithStatusAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)
Microsoft.Bot.Builder.Integration.AspNet.Core.CloudAdapter: Information: SendActivitiesAsync for 1 activities.
Microsoft.Bot.Builder.Integration.AspNet.Core.CloudAdapter: Information: Sending activity.  ReplyToId: 1698632502514
```

**Comment by raych1** [comment]
This is a bug of Teams-AI library. I disabled the moderator for short term solution as it's not needed in current scenario where the response of AI is based on the knowledge base.
